### ISSUE TITLE
Error: invalid_request after login

### ISSUE THREAD

**Issue by davidshq** [OpenImaging/miqa-web#14]
1. I have django miqa up and running using the included docker-compose files on my local system (Ubuntu 20.04).
2. I also cloned miqa-web onto my local system. I'm running node 14.16.1. 
3. I performed `npm install` and then `npm run serve`.
4. I navigate to http://localhost:8081/ and it properly loads the credentials
5. It redirects me to:
> http://localhost:8000/accounts/login/?next=/oauth/authorize/%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%253A8081%252F%26client_id%3DcBmD6D6F2YAmMWHNQZFPUr4OpaXVpW5w4Thod6Kj%26response_type%3Dcode%26state%3D3Ihh5Z9VoJ%26response_mode%3Dquery%26code_challenge%3DteCu5YVMhL8ahnXzLu9zK43-ShoErfNI92x0XVVzE8E%26code_challenge_method%3DS256

With HTML entities decoded and some line breaks for formatting:

> http://localhost:8000/accounts/login/?next=/oauth/authorize/
> ?redirect_uri=http%3A%2F%2Flocalhost%3A8081%2F
> &client_id=cBmD6D6F2YAmMWHNQZFPUr4OpaXVpW5w4Thod6Kj
> &response_type=code
> &state=3Ihh5Z9VoJ
> &response_mode=query
> &code_challenge=teCu5YVMhL8ahnXzLu9zK43-ShoErfNI92x0XVVzE8E
> &code_challenge_method=S256

6. After logging in I'm redirected to:
> http://localhost:8000/oauth/authorize/?redirect_uri=http%3A%2F%2Flocalhost%3A8081%2F&client_id=cBmD6D6F2YAmMWHNQZFPUr4OpaXVpW5w4Thod6Kj&response_type=code&state=lr7yE4DBsV&response_mode=query&code_challenge=5p_c3qkYEAv0z5fIBl0sJy3MWbL3qosJ6Mk-R_O2j-Y&code_challenge_method=S256

Pretty formatted:
> http://localhost:8000/oauth/authorize/?
> redirect_uri=http://localhost:8081/
> &client_id=cBmD6D6F2YAmMWHNQZFPUr4OpaXVpW5w4Thod6Kj
> &response_type=code
> &state=lr7yE4DBsV
> &response_mode=query
> &code_challenge=5p_c3qkYEAv0z5fIBl0sJy3MWbL3qosJ6Mk-R_O2j-Y
> &code_challenge_method=S256

(state and code_challenge values have changed from 1st url)

And the page displays the error:

> Error: invalid_request
> Invalid client_id parameter value.

Not sure if anyone else has experienced this? I'm going to blow away my django backend and try a completely new install and see if that makes a difference.

Help is welcome, but mainly I wanted to record this here in case anyone else runs into the same problem. I'll update this issue as I progress.

## Running Application Maintenance
Below I start fresh with django miqa I realized I should walk through the maintenance steps in the `README.md`. I did. I then used `docker-compose up` and navigated to http://localhost:8081, I briefly saw the Vue UI and then was redirected to localhost:8000 with the same error.

I then tried stopping the Vue frontend and restarting it. This did not resolve the issue.

**Comment by venkatabhishek** [comment]
This is a common problem, basically you have to create an oauth client. Assuming you already have the backend setup, you can follow steps 3-5 under the frontend section in [this document](https://github.com/OpenImaging/miqa/blob/master/development.md)

**Comment by davidshq** [comment]
Thanks! Running steps 3-5  as you suggested allowed the UI to load successfully (mainly). 

I'm getting one warning and one error in my browser console:


Warning:
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in created hook (Promise/async): "TypeError: Cannot read property 'id' of undefined"

found in

---> <Dataset> at src/views/Dataset.vue
       <VMain>
         <VApp>
           <App> at src/App.vue
             <Root>
```

Error:
```
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'id' of undefined
    at Store.loadSessions (index.js:formatted:494)
```

And clicking on the Login link at the top right of the screen does nothing.

Should the broken link in the README.md under "Development" be updated to point to the URL you provided?

**Comment by zachmullen** [comment]
I think that error may be because you don't have any sessions in your system. I'll file a ticket.

**Comment by davidshq** [comment]
PR #17 provides an updated link for the documentation so folks have frontend setup instructions available.

Issue #15 by @zachmullen covers issue that arises when no sessions are in the system.

I'm good with closing this ticket if PR #17 is merged.
